const MAX_BATCH=8, BATCH_DELAY=700, RETRY_MS=15000;
const processed=new Map(),pending=new Set(),queue=new Map(),visible=new Set();
let batchTimer=null,scanTimer=null,lastUrl=location.href,currentWatch='';
const CLEAN={hideTopicChips:false,hideNotificationBell:false,hideHomeFeed:false,hideRecommendedVideos:false,hideExplore:false,hideSubscriptionsBar:false,hideSidebar:false,hideShorts:false,hideRelatedVideos:false,hideComments:false,hideLiveChat:false,hideHistory:false,hidePlaylists:false};
let cfg={focusEnabled:true,hideWhileChecking:false,useGroq:true,cleanerEnabled:true,allowedChannels:[],blockedChannels:[],allowedTitlePhrases:[],blockedTitlePhrases:[],cleaner:{...CLEAN}};
const CARDS=['ytd-rich-item-renderer','ytd-video-renderer','ytd-compact-video-renderer','ytd-grid-video-renderer','ytd-playlist-video-renderer','ytd-reel-item-renderer','ytd-rich-grid-media','ytd-rich-grid-slim-media','yt-lockup-view-model','yt-lockup-metadata-view-model'].join(',');
const LINKS='a[href*="/watch?v="],a[href*="/shorts/"]';
const send=m=>new Promise(r=>{try{chrome.runtime.sendMessage(m,x=>{if(chrome.runtime.lastError)r({ok:false,error:chrome.runtime.lastError.message});else r(x||{ok:false,error:'No response'});});}catch(e){r({ok:false,error:e.message});}});
function norm(t){return String(t||'').toLowerCase().normalize('NFKC').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').replace(/\s+/g,' ').trim();}
function match(t,a){const x=norm(t);for(const q of a||[]){const n=norm(q);if(n&&x.includes(n))return q;}return '';}
function manual(v){
  let q=match(v.channel,cfg.allowedChannels); if(q)return{decided:true,block:false,category:'allowed channel',reason:`Allowed channel matched: ${q}`,source:'Manual filter'};
  q=match(v.channel,cfg.blockedChannels); if(q)return{decided:true,block:true,category:'blocked channel',reason:`Blocked channel matched: ${q}`,source:'Manual filter'};
  q=match(v.title,cfg.blockedTitlePhrases); if(q)return{decided:true,block:true,category:'blocked title',reason:`Blocked title phrase matched: ${q}`,source:'Manual filter'};
  q=match(v.title,cfg.allowedTitlePhrases); if(q)return{decided:true,block:false,category:'allowed title',reason:`Allowed title phrase matched: ${q}`,source:'Manual filter'};
  return{decided:false};
}
async function load(){const d=await chrome.storage.local.get({focusEnabled:true,hideWhileChecking:false,useGroq:true,cleanerEnabled:true,allowedChannels:[],blockedChannels:[],allowedTitlePhrases:[],blockedTitlePhrases:[],cleaner:CLEAN});cfg={focusEnabled:d.focusEnabled!==false,hideWhileChecking:d.hideWhileChecking===true,useGroq:d.useGroq!==false,cleanerEnabled:d.cleanerEnabled!==false,allowedChannels:Array.isArray(d.allowedChannels)?d.allowedChannels:[],blockedChannels:Array.isArray(d.blockedChannels)?d.blockedChannels:[],allowedTitlePhrases:Array.isArray(d.allowedTitlePhrases)?d.allowedTitlePhrases:[],blockedTitlePhrases:Array.isArray(d.blockedTitlePhrases)?d.blockedTitlePhrases:[],cleaner:{...CLEAN,...(d.cleaner||{})}};applyCleaner();}
function applyCleaner(){const r=document.documentElement,c=cfg.cleaner||CLEAN,m={hideTopicChips:'sf-hide-topic-chips',hideNotificationBell:'sf-hide-notification-bell',hideHomeFeed:'sf-hide-home-feed',hideRecommendedVideos:'sf-hide-recommended-videos',hideExplore:'sf-hide-explore',hideSubscriptionsBar:'sf-hide-subscriptions-bar',hideSidebar:'sf-hide-sidebar',hideShorts:'sf-hide-shorts',hideRelatedVideos:'sf-hide-related-videos',hideComments:'sf-hide-comments',hideLiveChat:'sf-hide-live-chat',hideHistory:'sf-hide-history',hidePlaylists:'sf-hide-playlists'};for(const[k,v]of Object.entries(m))r.classList.toggle(v,cfg.cleanerEnabled&&!!c[k]);markSubs();}
function markSubs(){document.querySelectorAll('ytd-guide-section-renderer').forEach(s=>{const h=norm(s.querySelector('#guide-section-title,h3 yt-formatted-string,h3')?.textContent||'');s.classList.toggle('sf-subscriptions-section',h==='subscriptions'||h==='الاشتراكات');});}
chrome.storage.onChanged.addListener(async(ch,a)=>{if(a!=='local')return;const keys=['focusEnabled','hideWhileChecking','useGroq','cleanerEnabled','allowedChannels','blockedChannels','allowedTitlePhrases','blockedTitlePhrases','cleaner'];if(!keys.some(k=>ch[k]))return;await load();processed.clear();pending.clear();queue.clear();document.querySelectorAll('[data-study-focus-key]').forEach(allow);currentWatch='';scan(document);watch();});
function vid(url){try{const u=new URL(url,location.origin);if(u.pathname==='/watch')return u.searchParams.get('v')||'';if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||'';}catch(e){}return'';}
function text(root,ss){for(const s of ss){try{const e=root.querySelector(s);const t=e?.getAttribute?.('title')?.trim()||e?.textContent?.trim()||e?.getAttribute?.('aria-label')?.trim();if(t)return t;}catch(e){}}return'';}
function bestLink(c){const a=[...c.querySelectorAll(LINKS)];return a.find(x=>(x.getAttribute('href')||'').includes('/watch?v='))||a[0]||null;}
function info(c){if(!c?.isConnected)return null;const a=bestLink(c);if(!a)return null;const url=a.href||a.getAttribute('href');if(!url)return null;const title=text(c,['#video-title','#video-title-link','h3','h4','.yt-lockup-metadata-view-model__title','.yt-lockup-metadata-view-model-wiz__title','yt-formatted-string[title]','[class*=title]'])||a.getAttribute?.('title')?.trim()||a.textContent?.trim()||'';if(!title)return null;const channel=text(c,['ytd-channel-name #text','#channel-name #text','#byline','.ytd-channel-name','.yt-content-metadata-view-model-wiz__metadata-row','.yt-lockup-metadata-view-model__metadata span','[class*=channel]']);const description=text(c,['#description-text','.metadata-snippet-text','.yt-lockup-metadata-view-model__metadata','.yt-lockup-metadata-view-model-wiz__metadata','#metadata-line']);const videoId=vid(url);return{title:title.slice(0,500),channel:channel.slice(0,300),description:description.slice(0,900),url,videoId,key:videoId||url+'|'+title};}
function cardFor(a){return a?.closest(CARDS)||a?.closest('[class*=lockup]')||a?.closest('[class*=video-renderer]')||a?.closest('[class*=rich-item]')||null;}
function cards(root=document){const s=new Set();try{root.querySelectorAll?.(CARDS).forEach(x=>s.add(x));root.querySelectorAll?.(LINKS).forEach(a=>{const c=cardFor(a);if(c)s.add(c);});}catch(e){}return s;}
function rm(c){const n=c?.nextElementSibling;if(n?.dataset?.studyFocusPlaceholder==='1')n.remove();}
function allow(c){if(!c)return;c.classList.remove('study-focus-hidden','study-focus-pending-hidden');c.dataset.studyFocusBlocked='';rm(c);}
function esc(t){return String(t||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));}
function block(c,r){if(!c)return;c.classList.remove('study-focus-pending-hidden');c.classList.add('study-focus-hidden');c.dataset.studyFocusBlocked='1';rm(c);const p=document.createElement('div');p.className='study-focus-blocked-card';p.dataset.studyFocusPlaceholder='1';p.innerHTML=`<strong>Study Focus blocked this</strong><span>${esc(r.category)} — ${esc(r.reason)}</span><small>Decision: ${esc(r.source)}</small>`;c.insertAdjacentElement('afterend',p);}
function pend(c){if(!cfg.hideWhileChecking||!c)return;c.classList.add('study-focus-pending-hidden');rm(c);const p=document.createElement('div');p.className='study-focus-checking-card';p.dataset.studyFocusPlaceholder='1';p.innerHTML='<strong>Study Focus is checking this video…</strong><span>Groq is deciding because no manual filter matched.</span>';c.insertAdjacentElement('afterend',p);}
function setKey(c,k){const o=c.dataset.studyFocusKey||'';if(o&&o!==k)allow(c);c.dataset.studyFocusKey=k;}
function same(k){return[...document.querySelectorAll('[data-study-focus-key]')].filter(c=>c.dataset.studyFocusKey===k);}
function apply(k,r){for(const c of same(k))r.block?block(c,r):allow(c);}
async function cached(v){const r=await send({type:'GET_CACHED_DECISION',video:v});return r?.ok?r.result:null;}
function scheduleBatch(){if(batchTimer)return;batchTimer=setTimeout(()=>{batchTimer=null;flush();},BATCH_DELAY);}
function enqueue(v){if(!cfg.useGroq)return;if(processed.has(v.key)||pending.has(v.key))return;pending.add(v.key);queue.set(v.key,v);same(v.key).forEach(pend);scheduleBatch();}
async function flush(){if(!queue.size)return;const sel=[...queue.entries()].slice(0,MAX_BATCH);sel.forEach(([k])=>queue.delete(k));const vs=sel.map(([k,v],i)=>({...v,clientId:`${Date.now()}-${i}-${Math.random().toString(36).slice(2,7)}`}));const r=await send({type:'GROQ_CLASSIFY_BATCH',videos:vs});if(!r?.ok){console.warn('[Study Focus V6] Groq failed:',r?.error);for(const v of vs){pending.delete(v.key);same(v.key).forEach(allow);}setTimeout(()=>{for(const v of vs)if(!processed.has(v.key)&&!pending.has(v.key))enqueue(v);},RETRY_MS);}else{const m=new Map((r.results||[]).map(x=>[x.id,x.result]));for(const v of vs){const res=m.get(v.clientId)||{block:false,category:'unknown',reason:'No AI decision returned.',source:'Groq'};processed.set(v.key,res);pending.delete(v.key);apply(v.key,res);}}if(queue.size)scheduleBatch();}
async function process(c){if(!c?.isConnected||c.dataset.studyFocusPlaceholder==='1')return;const v=info(c);if(!v?.key)return;setKey(c,v.key);if(!cfg.focusEnabled){allow(c);return;}const md=manual(v);if(md.decided){processed.set(v.key,md);if(md.block){block(c,md);send({type:'LOG_MANUAL_BLOCK',video:v,category:md.category,reason:md.reason});}else allow(c);return;}if(processed.has(v.key)){apply(v.key,processed.get(v.key));return;}if(pending.has(v.key)){if(cfg.hideWhileChecking)pend(c);return;}const ca=await cached(v);if(ca){processed.set(v.key,ca);apply(v.key,ca);return;}if(!cfg.useGroq){allow(c);return;}enqueue(v);}
const io=new IntersectionObserver(es=>{for(const e of es){if(e.isIntersecting){visible.add(e.target);process(e.target);}else visible.delete(e.target);}}, {rootMargin:'850px 0px 850px 0px'});
function observe(c){if(!c||c.dataset.studyFocusObserved==='1')return;c.dataset.studyFocusObserved='1';io.observe(c);}
function scan(root=document){markSubs();for(const c of cards(root)){observe(c);process(c);}}
function scanVisible(){for(const c of visible){if(c?.isConnected)process(c);else visible.delete(c);}}
function watchInfo(){const p=new URLSearchParams(location.search),videoId=p.get('v')||'';if(!videoId)return null;const title=document.querySelector('ytd-watch-metadata h1 yt-formatted-string')?.textContent?.trim()||document.querySelector('h1 yt-formatted-string')?.textContent?.trim()||document.title.replace(/\s*-\s*YouTube\s*$/,'').trim();const channel=document.querySelector('ytd-watch-metadata ytd-channel-name #text')?.textContent?.trim()||document.querySelector('#owner #channel-name #text')?.textContent?.trim()||'';const description=document.querySelector('ytd-text-inline-expander #description-inline-expander')?.textContent?.trim()?.slice(0,900)||document.querySelector('#description')?.textContent?.trim()?.slice(0,900)||'';return{title,channel,description,videoId,url:location.href,key:videoId};}
function rmOverlay(){document.getElementById('study-focus-watch-overlay')?.remove();}
function overlay(r){rmOverlay();const x=document.createElement('div');x.id='study-focus-watch-overlay';x.innerHTML=`<div class="box"><h2>Study Focus blocked this video</h2><p>${esc(r.category)} — ${esc(r.reason)}</p><p>Decision: ${esc(r.source)}</p><button id="sf-back">Go back</button></div>`;document.documentElement.appendChild(x);document.querySelector('video')?.pause();x.querySelector('#sf-back')?.addEventListener('click',()=>history.length>1?history.back():location.href='https://www.youtube.com/');}
async function watch(){if(location.pathname!=='/watch'){currentWatch='';rmOverlay();return;}const v=watchInfo();if(!v?.videoId||!v.title||currentWatch===v.videoId)return;currentWatch=v.videoId;if(!cfg.focusEnabled){rmOverlay();return;}const md=manual(v);if(md.decided){processed.set(v.key,md);if(md.block){overlay(md);send({type:'LOG_MANUAL_BLOCK',video:v,category:md.category,reason:md.reason});}else rmOverlay();return;}let r=processed.get(v.key)||await cached(v);if(r){processed.set(v.key,r);r.block?overlay(r):rmOverlay();return;}if(!cfg.useGroq){rmOverlay();return;}enqueue(v);}
function nav(){currentWatch='';rmOverlay();applyCleaner();}
function sched(root=document){clearTimeout(scanTimer);scanTimer=setTimeout(()=>{scan(root);scanVisible();watch();},140);}
const mo=new MutationObserver(ms=>{let rs=false;for(const m of ms){if(m.type==='childList'){for(const n of m.addedNodes)if(n instanceof Element)scan(n);rs=true;}if(m.type==='attributes'&&m.target instanceof Element){const a=m.target.matches?.(LINKS)?m.target:m.target.closest?.(LINKS);const c=m.target.closest?.(CARDS)||cardFor(a);if(c)process(c);}}if(rs)sched(document);});
mo.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['href','title','aria-label']});
window.addEventListener('yt-navigate-start',nav);window.addEventListener('yt-navigate-finish',()=>{nav();sched(document);});window.addEventListener('yt-page-data-updated',()=>sched(document));window.addEventListener('popstate',()=>{nav();sched(document);});window.addEventListener('scroll',()=>sched(document),{passive:true});
setInterval(()=>{if(location.href!==lastUrl){lastUrl=location.href;nav();sched(document);}},500);setInterval(()=>{scan(document);scanVisible();watch();},1800);
load().then(()=>{console.log('[Study Focus V6.3] loaded',cfg);scan(document);watch();});
