const DEF='openai/gpt-oss-20b'; const CLEAN={hideTopicChips:false,hideNotificationBell:false,hideHomeFeed:false,hideRecommendedVideos:false,hideExplore:false,hideSubscriptionsBar:false,hideSidebar:false,hideShorts:false,hideRelatedVideos:false,hideComments:false,hideLiveChat:false,hideHistory:false,hidePlaylists:false};
const state={allowedChannels:[],blockedChannels:[],allowedTitlePhrases:[],blockedTitlePhrases:[]};
const $=id=>document.getElementById(id); const send=m=>new Promise(r=>chrome.runtime.sendMessage(m,x=>{if(chrome.runtime.lastError)r({ok:false,error:chrome.runtime.lastError.message});else r(x||{ok:false,error:'No response'});}));
function uniq(a){const s=new Set(),o=[];for(const x of a||[]){const v=String(x||'').trim(),k=v.toLowerCase();if(v&&!s.has(k)){s.add(k);o.push(v);}}return o;}
function render(k){const c=$(k+'Tags');c.innerHTML='';for(const v of state[k]){const t=document.createElement('span');t.className='tag';const tx=document.createElement('span');tx.textContent=v;const b=document.createElement('button');b.textContent='×';b.onclick=async()=>{state[k]=state[k].filter(x=>x!==v);await chrome.storage.local.set({[k]:state[k]});render(k);};t.append(tx,b);c.appendChild(t);}}
async function add(k){const i=$(k+'Input'),v=i.value.trim();if(!v)return;state[k]=uniq([...state[k],v]);i.value='';await chrome.storage.local.set({[k]:state[k]});render(k);}
async function load(){const d=await chrome.storage.local.get({focusEnabled:true,hideWhileChecking:false,useGroq:true,cleanerEnabled:true,groqApiKey:'',groqModel:DEF,allowedChannels:[],blockedChannels:[],allowedTitlePhrases:[],blockedTitlePhrases:[],cleaner:CLEAN});$('useGroq').checked=d.useGroq!==false;$('cleanerEnabled').checked=d.cleanerEnabled!==false;$('focusEnabled').checked=d.focusEnabled!==false;$('hideWhileChecking').checked=d.hideWhileChecking===true;$('groqApiKey').value=d.groqApiKey||'';for(const k of Object.keys(state)){state[k]=uniq(d[k]);render(k);}if(![...$('groqModel').options].some(o=>o.value===d.groqModel)){const o=document.createElement('option');o.value=d.groqModel||DEF;o.textContent=o.value;$('groqModel').appendChild(o);}$('groqModel').value=d.groqModel||DEF;const c={...CLEAN,...(d.cleaner||{})};document.querySelectorAll('[data-cleaner]').forEach(i=>i.checked=!!c[i.dataset.cleaner]);}
async function saveCore(){await chrome.storage.local.set({focusEnabled:$('focusEnabled').checked,hideWhileChecking:$('hideWhileChecking').checked,useGroq:$('useGroq').checked,cleanerEnabled:$('cleanerEnabled').checked});}
async function saveCleaner(msg='Cleaner settings saved.'){const c={...CLEAN};document.querySelectorAll('[data-cleaner]').forEach(i=>c[i.dataset.cleaner]=i.checked);await chrome.storage.local.set({cleaner:c});$('cleanerStatus').textContent=msg;}
function models(a,sel){$('groqModel').innerHTML='';for(const m of a){const o=document.createElement('option');o.value=m;o.textContent=m;$('groqModel').appendChild(o);} $('groqModel').value=a.includes(sel)?sel:(a.includes(DEF)?DEF:(a[0]||''));}
$('useGroq').onchange=saveCore;$('cleanerEnabled').onchange=saveCore;$('focusEnabled').onchange=saveCore;$('hideWhileChecking').onchange=saveCore;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));for(const k of Object.keys(state))$(k+'Input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();add(k);}};document.querySelectorAll('[data-cleaner]').forEach(i=>i.onchange=()=>saveCleaner());
$('refreshModels').onclick=async()=>{const key=$('groqApiKey').value.trim();$('groqStatus').textContent='Loading models…';const r=await send({type:'GROQ_LIST_MODELS',apiKey:key});if(!r?.ok){$('groqStatus').textContent='❌ '+(r?.error||'Failed');return;}models(r.models,$('groqModel').value);$('groqStatus').textContent=`✅ Loaded ${r.models.length} models.`;};
$('saveTest').onclick=async()=>{const key=$('groqApiKey').value.trim();if(!key){$('groqStatus').textContent='❌ Enter Groq API key.';return;}$('groqStatus').textContent='Testing…';const r=await send({type:'GROQ_TEST',apiKey:key,model:$('groqModel').value});if(!r?.ok){$('groqStatus').textContent='❌ TEST FAILED\n'+(r?.error||'Unknown');return;}models(r.models,r.model);await chrome.storage.local.set({groqApiKey:key,groqModel:r.model,useGroq:true});$('useGroq').checked=true;$('groqStatus').textContent=`✅ GROQ WORKING\nModel: ${r.model}`;};
$('starter').onclick=async()=>{state.allowedTitlePhrases=uniq([...state.allowedTitlePhrases,'tutorial','lecture','course','محاضرة','شرح جافا','شرح بايثون','حل مسائل','music','song','موسيقى','اغاني','أغاني']);state.blockedTitlePhrases=uniq([...state.blockedTitlePhrases,'ملخص فيلم','تلخيص فيلم','شرح فيلم','مسلسل','gameplay','vlog','ميمز','مقلب']);await chrome.storage.local.set({allowedTitlePhrases:state.allowedTitlePhrases,blockedTitlePhrases:state.blockedTitlePhrases});render('allowedTitlePhrases');render('blockedTitlePhrases');};
$('clearFilters').onclick=async()=>{for(const k of Object.keys(state))state[k]=[];await chrome.storage.local.set({allowedChannels:[],blockedChannels:[],allowedTitlePhrases:[],blockedTitlePhrases:[]});for(const k of Object.keys(state))render(k);};
$('preset').onclick=async()=>{const p={hideTopicChips:true,hideNotificationBell:true,hideHomeFeed:false,hideRecommendedVideos:false,hideExplore:true,hideSubscriptionsBar:false,hideSidebar:false,hideShorts:true,hideRelatedVideos:true,hideComments:true,hideLiveChat:true,hideHistory:false,hidePlaylists:false};document.querySelectorAll('[data-cleaner]').forEach(i=>i.checked=!!p[i.dataset.cleaner]);await saveCleaner('Focus preset applied.');};
$('showAll').onclick=async()=>{document.querySelectorAll('[data-cleaner]').forEach(i=>i.checked=false);await saveCleaner('All YouTube elements visible.');};
$('clearCache').onclick=async()=>{const r=await send({type:'CLEAR_DECISION_CACHE'});$('toolStatus').textContent=r?.ok?`Cleared ${r.removed} cached decisions.`:'Could not clear cache.';};$('openLogs').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('logs.html')});$('resetStats').onclick=async()=>{const r=await send({type:'RESET_STATS'});$('toolStatus').textContent=r?.ok?'Statistics reset.':'Failed.';};
load();
